import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

const _kLocaleStorageKey = '__locale_key__';

class FFLocalizations {
  FFLocalizations(this.locale);

  final Locale locale;

  static FFLocalizations of(BuildContext context) =>
      Localizations.of<FFLocalizations>(context, FFLocalizations)!;

  static List<String> languages() =>
      ['ko', 'en', 'ja', 'zh_Hans', 'vi', 'fr', 'ru', 'ms'];

  static late SharedPreferences _prefs;
  static Future initialize() async =>
      _prefs = await SharedPreferences.getInstance();
  static Future storeLocale(String locale) =>
      _prefs.setString(_kLocaleStorageKey, locale);
  static Locale? getStoredLocale() {
    final locale = _prefs.getString(_kLocaleStorageKey);
    return locale != null && locale.isNotEmpty ? createLocale(locale) : null;
  }

  String get languageCode => locale.toString();
  String? get languageShortCode =>
      _languagesWithShortCode.contains(locale.toString())
          ? '${locale.toString()}_short'
          : null;
  int get languageIndex => languages().contains(languageCode)
      ? languages().indexOf(languageCode)
      : 0;

  String getText(String key) =>
      (kTranslationsMap[key] ?? {})[locale.toString()] ?? '';

  String getVariableText({
    String? koText = '',
    String? enText = '',
    String? jaText = '',
    String? zh_HansText = '',
    String? viText = '',
    String? frText = '',
    String? ruText = '',
    String? msText = '',
  }) =>
      [
        koText,
        enText,
        jaText,
        zh_HansText,
        viText,
        frText,
        ruText,
        msText
      ][languageIndex] ??
      '';

  static const Set<String> _languagesWithShortCode = {
    'ar',
    'az',
    'ca',
    'cs',
    'da',
    'de',
    'dv',
    'en',
    'es',
    'et',
    'fi',
    'fr',
    'gr',
    'he',
    'hi',
    'hu',
    'it',
    'km',
    'ku',
    'mn',
    'ms',
    'no',
    'pt',
    'ro',
    'ru',
    'rw',
    'sv',
    'th',
    'uk',
    'vi',
  };
}

class FFLocalizationsDelegate extends LocalizationsDelegate<FFLocalizations> {
  const FFLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    final language = locale.toString();
    return FFLocalizations.languages().contains(
      language.endsWith('_')
          ? language.substring(0, language.length - 1)
          : language,
    );
  }

  @override
  Future<FFLocalizations> load(Locale locale) =>
      SynchronousFuture<FFLocalizations>(FFLocalizations(locale));

  @override
  bool shouldReload(FFLocalizationsDelegate old) => false;
}

Locale createLocale(String language) => language.contains('_')
    ? Locale.fromSubtags(
        languageCode: language.split('_').first,
        scriptCode: language.split('_').last,
      )
    : Locale(language);

final kTranslationsMap = <Map<String, Map<String, String>>>[
  // login
  {
    'asi8li8l': {
      'ko': '로그인',
      'en': 'log in',
      'fr': 'connexion',
      'ja': 'ログイン',
      'ms': 'log masuk',
      'ru': 'авторизоваться',
      'vi': 'đăng nhập',
      'zh_Hans': '登录',
    },
    't8qg4843': {
      'ko': '이메일',
      'en': 'email',
      'fr': 'e-mail',
      'ja': 'Eメール',
      'ms': 'emel',
      'ru': 'электронное письмо',
      'vi': 'e-mail',
      'zh_Hans': '电子邮件',
    },
    'y8930bhw': {
      'ko': '이메일',
      'en': 'email',
      'fr': 'e-mail',
      'ja': 'Eメール',
      'ms': 'emel',
      'ru': 'электронное письмо',
      'vi': 'e-mail',
      'zh_Hans': '电子邮件',
    },
    'vkjdtstj': {
      'ko': '비밀번호',
      'en': 'password',
      'fr': 'le mot de passe',
      'ja': 'パスワード',
      'ms': 'kata laluan',
      'ru': 'пароль',
      'vi': 'mật khẩu mở khóa',
      'zh_Hans': '密码',
    },
    'x1zg43fh': {
      'ko': '비밀번호',
      'en': 'password',
      'fr': 'le mot de passe',
      'ja': 'パスワード',
      'ms': 'kata laluan',
      'ru': 'пароль',
      'vi': 'mật khẩu mở khóa',
      'zh_Hans': '密码',
    },
    'd493nanu': {
      'ko': '로그인',
      'en': 'log in',
      'fr': 'connexion',
      'ja': 'ログイン',
      'ms': 'log masuk',
      'ru': 'авторизоваться',
      'vi': 'đăng nhập',
      'zh_Hans': '登录',
    },
    'dqag5uk7': {
      'ko': '아이디/비밀번호 찾기',
      'en': 'Find ID/Password',
      'fr': 'Trouver identifiant/mot de passe',
      'ja': 'ID/パスワードを探す',
      'ms': 'Cari ID/Kata Laluan',
      'ru': 'Найти идентификатор/пароль',
      'vi': 'Tìm ID/Mật khẩu',
      'zh_Hans': '查找 ID/密码',
    },
    'qbzgnquw': {
      'ko': '회원가입',
      'en': 'Sign Up',
      'fr': 'S\'inscrire',
      'ja': '会員登録',
      'ms': 'Daftar',
      'ru': 'Зарегистрироваться',
      'vi': 'Đăng ký',
      'zh_Hans': '报名',
    },
    '03n4fcz3': {
      'ko': 'Home',
      'en': 'Home',
      'fr': 'Domicile',
      'ja': 'ホーム',
      'ms': 'Rumah',
      'ru': 'Дом',
      'vi': 'Trang Chủ',
      'zh_Hans': '家',
    },
  },
  // findid
  {
    'cuq7wyf0': {
      'ko': '아이디 찾기',
      'en': 'find ID',
      'fr': 'trouver l\'identifiant',
      'ja': 'IDを探す',
      'ms': 'cari ID',
      'ru': 'найти идентификатор',
      'vi': 'tìm ID',
      'zh_Hans': '找身份证',
    },
    'cwoz6q1f': {
      'ko': '이름',
      'en': 'name',
      'fr': 'Nom',
      'ja': '名前',
      'ms': 'nama',
      'ru': 'имя',
      'vi': 'Tên',
      'zh_Hans': '姓名',
    },
    'tutpqlwn': {
      'ko': '이름',
      'en': 'name',
      'fr': 'Nom',
      'ja': '名前',
      'ms': 'nama',
      'ru': 'имя',
      'vi': 'Tên',
      'zh_Hans': '姓名',
    },
    'gsqudygt': {
      'ko': '연락처',
      'en': 'contact',
      'fr': 'Contactez',
      'ja': 'お問い合わせ',
      'ms': 'kenalan',
      'ru': 'контакт',
      'vi': 'liên hệ',
      'zh_Hans': '接触',
    },
    'rx8wqur2': {
      'ko': '연락처',
      'en': 'contact',
      'fr': 'Contactez',
      'ja': 'お問い合わせ',
      'ms': 'kenalan',
      'ru': 'контакт',
      'vi': 'liên hệ',
      'zh_Hans': '接触',
    },
    'os552y2j': {
      'ko': '이름과 연락처를 입력해주세요.',
      'en': 'Please enter your name and contact information.',
      'fr': 'Veuillez entrer votre nom et vos coordonnées.',
      'ja': '名前と連絡先を入力してください。',
      'ms': 'Sila masukkan nama dan maklumat hubungan anda.',
      'ru': 'Пожалуйста, введите свое имя и контактную информацию.',
      'vi': 'Vui lòng nhập tên và thông tin liên lạc của bạn.',
      'zh_Hans': '请输入您的姓名和联系信息。',
    },
    '83t6argm': {
      'ko': '확인',
      'en': 'Confirm',
      'fr': 'Confirmer',
      'ja': '確認',
      'ms': 'sahkan',
      'ru': 'Подтверждать',
      'vi': 'Xác nhận',
      'zh_Hans': '确认',
    },
    'mlva9tid': {
      'ko': '비밀번호 찾기',
      'en': 'Forgot your password',
      'fr': 'Mot de passe oublié',
      'ja': 'パスワードを探す',
      'ms': 'Terlupa kata laluan anda',
      'ru': 'Забыли пароль',
      'vi': 'Quên mật khẩu',
      'zh_Hans': '忘记密码了吗',
    },
    '8ufk2epj': {
      'ko': '회원가입',
      'en': 'Sign Up',
      'fr': 'S\'inscrire',
      'ja': '会員登録',
      'ms': 'Daftar',
      'ru': 'Зарегистрироваться',
      'vi': 'Đăng ký',
      'zh_Hans': '报名',
    },
    'qgho74nn': {
      'ko': '로그인',
      'en': 'log in',
      'fr': 'connexion',
      'ja': 'ログイン',
      'ms': 'log masuk',
      'ru': 'авторизоваться',
      'vi': 'đăng nhập',
      'zh_Hans': '登录',
    },
    '74oao9qt': {
      'ko': 'Home',
      'en': 'Home',
      'fr': 'Domicile',
      'ja': 'ホーム',
      'ms': 'Rumah',
      'ru': 'Дом',
      'vi': 'Trang Chủ',
      'zh_Hans': '家',
    },
  },
  // selectLang
  {
    'm6lke6r7': {
      'ko': '언어선택',
      'en': 'language selection',
      'fr': 'sélection de la langue',
      'ja': '言語選択',
      'ms': 'pemilihan bahasa',
      'ru': 'Выбор языка',
      'vi': 'sự lựa chọn ngôn ngữ',
      'zh_Hans': '语言选择',
    },
    'zimith80': {
      'ko': '자신의 모국어를 선택하세요.',
      'en': 'Choose your native language.',
      'fr': 'Choisissez votre langue maternelle.',
      'ja': '自分の母国語を選択してください。',
      'ms': 'Pilih bahasa ibunda anda.',
      'ru': 'Выберите свой родной язык.',
      'vi': 'Chọn ngôn ngữ mẹ đẻ của bạn.',
      'zh_Hans': '选择您的母语。',
    },
    'mq1urwsu': {
      'ko': '모국어를 선택하세요.',
      'en': 'Please select your native language.',
      'fr': 'Veuillez sélectionner votre langue maternelle.',
      'ja': '母国語を選択してください。',
      'ms': 'Sila pilih bahasa ibunda anda.',
      'ru': 'Пожалуйста, выберите ваш родной язык.',
      'vi': 'Vui lòng chọn ngôn ngữ mẹ đẻ của bạn.',
      'zh_Hans': '请选择您的母语。',
    },
    't8a1xv46': {
      'ko': '학습언어(현재 영어 지원)',
      'en': 'Study language (currently supports English)',
      'fr': 'Langue d\'étude (prend actuellement en charge l\'anglais)',
      'ja': '学習言語（現在英語サポート）',
      'ms': 'Belajar bahasa (kini menyokong bahasa Inggeris)',
      'ru': 'Язык обучения (в настоящее время поддерживается английский)',
      'vi': 'Ngôn ngữ học (hiện hỗ trợ tiếng Anh)',
      'zh_Hans': '学习语言（目前支持英语）',
    },
    'f2wbrb6e': {
      'ko': '영어',
      'en': 'english',
      'fr': 'Anglais',
      'ja': '英語',
      'ms': 'bahasa inggeris',
      'ru': 'английский',
      'vi': 'tiếng anh',
      'zh_Hans': '英语',
    },
    '5o30514t': {
      'ko': '영어',
      'en': 'english',
      'fr': 'Anglais',
      'ja': '英語',
      'ms': 'bahasa inggeris',
      'ru': 'английский',
      'vi': 'tiếng anh',
      'zh_Hans': '英语',
    },
    'npywyvs8': {
      'ko': '다음',
      'en': 'next',
      'fr': 'suivant',
      'ja': 'Next',
      'ms': 'seterusnya',
      'ru': 'следующий',
      'vi': 'tiếp theo',
      'zh_Hans': '下一个',
    },
    'b5m1a0iu': {
      'ko': 'Home',
      'en': 'Home',
      'fr': 'Domicile',
      'ja': 'ホーム',
      'ms': 'Rumah',
      'ru': 'Дом',
      'vi': 'Trang Chủ',
      'zh_Hans': '家',
    },
  },
  // selectLevel
  {
    'u1mvfhl9': {
      'ko': '단계선택',
      'en': 'step selection',
      'fr': 'sélection de l\'étape',
      'ja': 'ステップ選択',
      'ms': 'pemilihan langkah',
      'ru': 'выбор шага',
      'vi': 'lựa chọn bước',
      'zh_Hans': '步骤选择',
    },
    '4fp98a8s': {
      'ko': '학습 과정의 단계를 선택해주세요',
      'en': 'Please select a stage in the learning process',
      'fr': 'Veuillez sélectionner une étape du processus d\'apprentissage',
      'ja': '学習プロセスの段階を選択してください',
      'ms': 'Sila pilih peringkat dalam proses pembelajaran',
      'ru': 'Выберите этап обучения',
      'vi': 'Vui lòng chọn một giai đoạn trong quá trình học tập',
      'zh_Hans': '请选择学习过程中的一个阶段',
    },
    'q39kx6id': {
      'ko': '초급',
      'en': 'beginner',
      'fr': 'débutant',
      'ja': '初級',
      'ms': 'pemula',
      'ru': 'новичок',
      'vi': 'người bắt đầu',
      'zh_Hans': '初学者',
    },
    '62lsrg8f': {
      'ko': '중급',
      'en': 'Middle class',
      'fr': 'Classe moyenne',
      'ja': '中級',
      'ms': 'Kelas pertengahan',
      'ru': 'Средний класс',
      'vi': 'Tầng lớp trung lưu',
      'zh_Hans': '中产阶级',
    },
    'yq2ooehe': {
      'ko': '상급',
      'en': 'senior',
      'fr': 'Sénior',
      'ja': '上級',
      'ms': 'senior',
      'ru': 'старший',
      'vi': 'cao cấp',
      'zh_Hans': '高级的',
    },
    'roiz46fd': {
      'ko': 'Home',
      'en': 'Home',
      'fr': 'Domicile',
      'ja': 'ホーム',
      'ms': 'Rumah',
      'ru': 'Дом',
      'vi': 'Trang Chủ',
      'zh_Hans': '家',
    },
  },
  // selectCourse
  {
    'vtjzjmja': {
      'ko': '진행방식 선택',
      'en': 'Choose how to proceed',
      'fr': 'Choisissez comment procéder',
      'ja': '進行方式の選択',
      'ms': 'Pilih cara untuk meneruskan',
      'ru': 'Выберите, как действовать',
      'vi': 'Chọn cách tiến hành',
      'zh_Hans': '选择如何进行',
    },
    'uuof32p5': {
      'ko': '동사별은 문형선택이 없습니다.',
      'en': 'There is no sentence type choice for each verb.',
      'fr': 'Il n\'y a pas de choix de type de phrase pour chaque verbe.',
      'ja': '動詞別には文型選択はありません。',
      'ms': 'Tiada pilihan jenis ayat untuk setiap kata kerja.',
      'ru': 'Для каждого глагола нет выбора типа предложения.',
      'vi': 'Không có sự lựa chọn loại câu cho mỗi động từ.',
      'zh_Hans': '每个动词都没有句型选择。',
    },
    '3zenl928': {
      'ko': '문형별',
      'en': 'Hyungbyeol Moon',
      'fr': 'Lune Hyungbyeol',
      'ja': '文型別',
      'ms': 'Hyungbyeol Moon',
      'ru': 'Хёнбёль Мун',
      'vi': 'Mặt trăng Hyungbyeol',
      'zh_Hans': '文亨星',
    },
    'csw3iec1': {
      'ko': '동사별',
      'en': 'by verb',
      'fr': 'par verbe',
      'ja': '動詞別',
      'ms': 'dengan kata kerja',
      'ru': 'по глаголу',
      'vi': 'bằng động từ',
      'zh_Hans': '通过动词',
    },
    'ys92ll5v': {
      'ko': 'Home',
      'en': 'Home',
      'fr': 'Domicile',
      'ja': 'ホーム',
      'ms': 'Rumah',
      'ru': 'Дом',
      'vi': 'Trang Chủ',
      'zh_Hans': '家',
    },
  },
  // findpassword
  {
    '1u5i3scp': {
      'ko': '비밀번호 찾기',
      'en': 'Forgot your password',
      'fr': 'Mot de passe oublié',
      'ja': 'パスワードを探す',
      'ms': 'Terlupa kata laluan anda',
      'ru': 'Забыли пароль',
      'vi': 'Quên mật khẩu',
      'zh_Hans': '忘记密码了吗',
    },
    'hnlp1obk': {
      'ko': '이메일',
      'en': 'email',
      'fr': 'e-mail',
      'ja': 'Eメール',
      'ms': 'emel',
      'ru': 'электронное письмо',
      'vi': 'e-mail',
      'zh_Hans': '电子邮件',
    },
    'c06jd2uo': {
      'ko': '이메일',
      'en': 'email',
      'fr': 'e-mail',
      'ja': 'Eメール',
      'ms': 'emel',
      'ru': 'электронное письмо',
      'vi': 'e-mail',
      'zh_Hans': '电子邮件',
    },
    'a1pedazz': {
      'ko': '입력하신 이메일 주소로 임시 비밀번호를 발송해 드립니다. 로그인 후 비밀번호를 수정해주세[요',
      'en':
          'A temporary password will be sent to the email address you entered. Please correct your password after logging in [Yo',
      'fr':
          'Un mot de passe temporaire sera envoyé à l\'adresse e-mail que vous avez saisie. Veuillez corriger votre mot de passe après vous être connecté [Yo',
      'ja': 'ご入力いただいたメールアドレスに仮パスワードをお送りします。ログインしてパスワードを編集してください[',
      'ms':
          'Kata laluan sementara akan dihantar ke alamat e-mel yang anda masukkan. Sila betulkan kata laluan anda selepas log masuk [Yo',
      'ru':
          'Временный пароль будет отправлен на указанный вами адрес электронной почты. Пожалуйста, исправьте свой пароль после входа в систему [Yo',
      'vi':
          'Một mật khẩu tạm thời sẽ được gửi đến địa chỉ email bạn đã nhập. Vui lòng sửa lại mật khẩu của bạn sau khi đăng nhập [Yo',
      'zh_Hans': '一个临时密码将发送到您输入的电子邮件地址。登录后请修改密码【哟',
    },
    'ytmdyx3t': {
      'ko': '확인',
      'en': 'Confirm',
      'fr': 'Confirmer',
      'ja': '確認',
      'ms': 'sahkan',
      'ru': 'Подтверждать',
      'vi': 'Xác nhận',
      'zh_Hans': '确认',
    },
    'a57an2oa': {
      'ko': '아이디 찾기',
      'en': 'find ID',
      'fr': 'trouver l\'identifiant',
      'ja': 'IDを探す',
      'ms': 'cari ID',
      'ru': 'найти идентификатор',
      'vi': 'tìm ID',
      'zh_Hans': '找身份证',
    },
    '35ll6sok': {
      'ko': '회원가입',
      'en': 'Sign Up',
      'fr': 'S\'inscrire',
      'ja': '会員登録',
      'ms': 'Daftar',
      'ru': 'Зарегистрироваться',
      'vi': 'Đăng ký',
      'zh_Hans': '报名',
    },
    'xva1qfnq': {
      'ko': '로그인',
      'en': 'log in',
      'fr': 'connexion',
      'ja': 'ログイン',
      'ms': 'log masuk',
      'ru': 'авторизоваться',
      'vi': 'đăng nhập',
      'zh_Hans': '登录',
    },
    'rqx6ez3i': {
      'ko': 'Home',
      'en': 'Home',
      'fr': 'Domicile',
      'ja': 'ホーム',
      'ms': 'Rumah',
      'ru': 'Дом',
      'vi': 'Trang Chủ',
      'zh_Hans': '家',
    },
  },
  // selectProcess
  {
    'gg0y747w': {
      'ko': '개별과정 선택',
      'en': 'Individual course selection',
      'fr': 'Sélection de cours individuels',
      'ja': '個別コースの選択',
      'ms': 'Pemilihan kursus individu',
      'ru': 'Индивидуальный подбор курса',
      'vi': 'Lựa chọn khóa học cá nhân',
      'zh_Hans': '个人选课',
    },
    'xm05ckfx': {
      'ko': '원하는 단계를 선택해주세요',
      'en': 'Please select the desired level',
      'fr': 'Veuillez sélectionner le niveau souhaité',
      'ja': '希望のステップを選択してください',
      'ms': 'Sila pilih tahap yang dikehendaki',
      'ru': 'Пожалуйста, выберите нужный уровень',
      'vi': 'Vui lòng chọn cấp độ mong muốn',
      'zh_Hans': '请选择所需级别',
    },
    'pemha42f': {
      'ko': '1',
      'en': 'One',
      'fr': 'Un',
      'ja': '1',
      'ms': 'satu',
      'ru': 'Один',
      'vi': 'Một',
      'zh_Hans': '一',
    },
    'clxdmk3w': {
      'ko': '2',
      'en': '2',
      'fr': '2',
      'ja': '2',
      'ms': '2',
      'ru': '2',
      'vi': '2',
      'zh_Hans': '2个',
    },
    'wx8w6uy0': {
      'ko': '3',
      'en': '3',
      'fr': '3',
      'ja': '3',
      'ms': '3',
      'ru': '3',
      'vi': '3',
      'zh_Hans': '3个',
    },
    '2epoc9kk': {
      'ko': '4',
      'en': '4',
      'fr': '4',
      'ja': '4',
      'ms': '4',
      'ru': '4',
      'vi': '4',
      'zh_Hans': '4个',
    },
    'glcwkxmn': {
      'ko': '5',
      'en': '5',
      'fr': '5',
      'ja': '5',
      'ms': '5',
      'ru': '5',
      'vi': '5',
      'zh_Hans': '5个',
    },
    '4hmw5x9z': {
      'ko': '6',
      'en': '6',
      'fr': '6',
      'ja': '6',
      'ms': '6',
      'ru': '6',
      'vi': '6',
      'zh_Hans': '6个',
    },
    '4sjkrr8d': {
      'ko': '7',
      'en': '7',
      'fr': '7',
      'ja': '7',
      'ms': '7',
      'ru': '7',
      'vi': '7',
      'zh_Hans': '7',
    },
    'nd6qd52t': {
      'ko': '8',
      'en': '8',
      'fr': '8',
      'ja': '8',
      'ms': '8',
      'ru': '8',
      'vi': 'số 8',
      'zh_Hans': '8个',
    },
    '03xmg0xx': {
      'ko': '9',
      'en': '9',
      'fr': '9',
      'ja': '9',
      'ms': '9',
      'ru': '9',
      'vi': '9',
      'zh_Hans': '9',
    },
    'p7ctstsh': {
      'ko': '1',
      'en': 'One',
      'fr': 'Un',
      'ja': '1',
      'ms': 'satu',
      'ru': 'Один',
      'vi': 'Một',
      'zh_Hans': '一',
    },
    '8z9rboix': {
      'ko': '1',
      'en': 'One',
      'fr': 'Un',
      'ja': '1',
      'ms': 'satu',
      'ru': 'Один',
      'vi': 'Một',
      'zh_Hans': '一',
    },
    'zvzzlpff': {
      'ko': '1',
      'en': 'One',
      'fr': 'Un',
      'ja': '1',
      'ms': 'satu',
      'ru': 'Один',
      'vi': 'Một',
      'zh_Hans': '一',
    },
    'gkz3sqj3': {
      'ko': '1',
      'en': 'One',
      'fr': 'Un',
      'ja': '1',
      'ms': 'satu',
      'ru': 'Один',
      'vi': 'Một',
      'zh_Hans': '一',
    },
    'lvdfn4gy': {
      'ko': '1',
      'en': 'One',
      'fr': 'Un',
      'ja': '1',
      'ms': 'satu',
      'ru': 'Один',
      'vi': 'Một',
      'zh_Hans': '一',
    },
    'rall489o': {
      'ko': '1',
      'en': 'One',
      'fr': 'Un',
      'ja': '1',
      'ms': 'satu',
      'ru': 'Один',
      'vi': 'Một',
      'zh_Hans': '一',
    },
    '4qojipqz': {
      'ko': '1',
      'en': 'One',
      'fr': 'Un',
      'ja': '1',
      'ms': 'satu',
      'ru': 'Один',
      'vi': 'Một',
      'zh_Hans': '一',
    },
    '5v181gk0': {
      'ko': '1',
      'en': 'One',
      'fr': 'Un',
      'ja': '1',
      'ms': 'satu',
      'ru': 'Один',
      'vi': 'Một',
      'zh_Hans': '一',
    },
    'ln83d9c2': {
      'ko': '1',
      'en': 'One',
      'fr': 'Un',
      'ja': '1',
      'ms': 'satu',
      'ru': 'Один',
      'vi': 'Một',
      'zh_Hans': '一',
    },
    'e7e80i4z': {
      'ko': '2',
      'en': '2',
      'fr': '2',
      'ja': '2',
      'ms': '2',
      'ru': '2',
      'vi': '2',
      'zh_Hans': '2个',
    },
    'e7wzjn1p': {
      'ko': '2',
      'en': '2',
      'fr': '2',
      'ja': '2',
      'ms': '2',
      'ru': '2',
      'vi': '2',
      'zh_Hans': '2个',
    },
    'isryuirb': {
      'ko': '2',
      'en': '2',
      'fr': '2',
      'ja': '2',
      'ms': '2',
      'ru': '2',
      'vi': '2',
      'zh_Hans': '2个',
    },
    '303hedj2': {
      'ko': '2',
      'en': '2',
      'fr': '2',
      'ja': '2',
      'ms': '2',
      'ru': '2',
      'vi': '2',
      'zh_Hans': '2个',
    },
    '5j2zz0uw': {
      'ko': '2',
      'en': '2',
      'fr': '2',
      'ja': '2',
      'ms': '2',
      'ru': '2',
      'vi': '2',
      'zh_Hans': '2个',
    },
    'jjlmjq6s': {
      'ko': '2',
      'en': '2',
      'fr': '2',
      'ja': '2',
      'ms': '2',
      'ru': '2',
      'vi': '2',
      'zh_Hans': '2个',
    },
    'sm2rbuan': {
      'ko': '2',
      'en': '2',
      'fr': '2',
      'ja': '2',
      'ms': '2',
      'ru': '2',
      'vi': '2',
      'zh_Hans': '2个',
    },
    '7erc7c8y': {
      'ko': '2',
      'en': '2',
      'fr': '2',
      'ja': '2',
      'ms': '2',
      'ru': '2',
      'vi': '2',
      'zh_Hans': '2个',
    },
    'vezp0j15': {
      'ko': '2',
      'en': '2',
      'fr': '2',
      'ja': '2',
      'ms': '2',
      'ru': '2',
      'vi': '2',
      'zh_Hans': '2个',
    },
    'cq2ndekk': {
      'ko': '3',
      'en': '3',
      'fr': '3',
      'ja': '3',
      'ms': '3',
      'ru': '3',
      'vi': '3',
      'zh_Hans': '3个',
    },
    '8vm1nuk3': {
      'ko': '3',
      'en': '3',
      'fr': '3',
      'ja': '3',
      'ms': '3',
      'ru': '3',
      'vi': '3',
      'zh_Hans': '3个',
    },
    'zb3n102i': {
      'ko': '3',
      'en': '3',
      'fr': '3',
      'ja': '3',
      'ms': '3',
      'ru': '3',
      'vi': '3',
      'zh_Hans': '3个',
    },
    'h6wgnvbn': {
      'ko': '3',
      'en': '3',
      'fr': '3',
      'ja': '3',
      'ms': '3',
      'ru': '3',
      'vi': '3',
      'zh_Hans': '3个',
    },
    'gi6ripjg': {
      'ko': '3',
      'en': '3',
      'fr': '3',
      'ja': '3',
      'ms': '3',
      'ru': '3',
      'vi': '3',
      'zh_Hans': '3个',
    },
    'oy5940m8': {
      'ko': '3',
      'en': '3',
      'fr': '3',
      'ja': '3',
      'ms': '3',
      'ru': '3',
      'vi': '3',
      'zh_Hans': '3个',
    },
    '664wx7eq': {
      'ko': '3',
      'en': '3',
      'fr': '3',
      'ja': '3',
      'ms': '3',
      'ru': '3',
      'vi': '3',
      'zh_Hans': '3个',
    },
    '3h5zvlk8': {
      'ko': '3',
      'en': '3',
      'fr': '3',
      'ja': '3',
      'ms': '3',
      'ru': '3',
      'vi': '3',
      'zh_Hans': '3个',
    },
    'dzkd8vge': {
      'ko': '3',
      'en': '3',
      'fr': '3',
      'ja': '3',
      'ms': '3',
      'ru': '3',
      'vi': '3',
      'zh_Hans': '3个',
    },
    'aqf6sptg': {
      'ko': '4',
      'en': '4',
      'fr': '4',
      'ja': '4',
      'ms': '4',
      'ru': '4',
      'vi': '4',
      'zh_Hans': '4个',
    },
    '84heqlqn': {
      'ko': '4',
      'en': '4',
      'fr': '4',
      'ja': '4',
      'ms': '4',
      'ru': '4',
      'vi': '4',
      'zh_Hans': '4个',
    },
    'ac9efryh': {
      'ko': '4',
      'en': '4',
      'fr': '4',
      'ja': '4',
      'ms': '4',
      'ru': '4',
      'vi': '4',
      'zh_Hans': '4个',
    },
    'xmlbakcz': {
      'ko': '4',
      'en': '4',
      'fr': '4',
      'ja': '4',
      'ms': '4',
      'ru': '4',
      'vi': '4',
      'zh_Hans': '4个',
    },
    '2x0lw62s': {
      'ko': '4',
      'en': '4',
      'fr': '4',
      'ja': '4',
      'ms': '4',
      'ru': '4',
      'vi': '4',
      'zh_Hans': '4个',
    },
    'jjdeswve': {
      'ko': '4',
      'en': '4',
      'fr': '4',
      'ja': '4',
      'ms': '4',
      'ru': '4',
      'vi': '4',
      'zh_Hans': '4个',
    },
    'qa7dopt3': {
      'ko': '4',
      'en': '4',
      'fr': '4',
      'ja': '4',
      'ms': '4',
      'ru': '4',
      'vi': '4',
      'zh_Hans': '4个',
    },
    'pmkq070e': {
      'ko': '4',
      'en': '4',
      'fr': '4',
      'ja': '4',
      'ms': '4',
      'ru': '4',
      'vi': '4',
      'zh_Hans': '4个',
    },
    'a1gwrr6y': {
      'ko': '4',
      'en': '4',
      'fr': '4',
      'ja': '4',
      'ms': '4',
      'ru': '4',
      'vi': '4',
      'zh_Hans': '4个',
    },
    'q91kil1n': {
      'ko': '5',
      'en': '5',
      'fr': '5',
      'ja': '5',
      'ms': '5',
      'ru': '5',
      'vi': '5',
      'zh_Hans': '5个',
    },
    'kbnkitky': {
      'ko': '5',
      'en': '5',
      'fr': '5',
      'ja': '5',
      'ms': '5',
      'ru': '5',
      'vi': '5',
      'zh_Hans': '5个',
    },
    'wt9nimu0': {
      'ko': '5',
      'en': '5',
      'fr': '5',
      'ja': '5',
      'ms': '5',
      'ru': '5',
      'vi': '5',
      'zh_Hans': '5个',
    },
    'xfsywpvm': {
      'ko': '5',
      'en': '5',
      'fr': '5',
      'ja': '5',
      'ms': '5',
      'ru': '5',
      'vi': '5',
      'zh_Hans': '5个',
    },
    'ccvkcpmi': {
      'ko': '5',
      'en': '5',
      'fr': '5',
      'ja': '5',
      'ms': '5',
      'ru': '5',
      'vi': '5',
      'zh_Hans': '5个',
    },
    '5sldtk95': {
      'ko': '5',
      'en': '5',
      'fr': '5',
      'ja': '5',
      'ms': '5',
      'ru': '5',
      'vi': '5',
      'zh_Hans': '5个',
    },
    'gnf67fh8': {
      'ko': '5',
      'en': '5',
      'fr': '5',
      'ja': '5',
      'ms': '5',
      'ru': '5',
      'vi': '5',
      'zh_Hans': '5个',
    },
    'al1v0ahn': {
      'ko': '5',
      'en': '5',
      'fr': '5',
      'ja': '5',
      'ms': '5',
      'ru': '5',
      'vi': '5',
      'zh_Hans': '5个',
    },
    '8l1lx5cw': {
      'ko': '5',
      'en': '5',
      'fr': '5',
      'ja': '5',
      'ms': '5',
      'ru': '5',
      'vi': '5',
      'zh_Hans': '5个',
    },
    'xe5u9c0d': {
      'ko': '6',
      'en': '6',
      'fr': '6',
      'ja': '6',
      'ms': '6',
      'ru': '6',
      'vi': '6',
      'zh_Hans': '6个',
    },
    'zf7rv2jc': {
      'ko': '6',
      'en': '6',
      'fr': '6',
      'ja': '6',
      'ms': '6',
      'ru': '6',
      'vi': '6',
      'zh_Hans': '6个',
    },
    'qz7p8c3r': {
      'ko': '6',
      'en': '6',
      'fr': '6',
      'ja': '6',
      'ms': '6',
      'ru': '6',
      'vi': '6',
      'zh_Hans': '6个',
    },
    'qb5huj7v': {
      'ko': '6',
      'en': '6',
      'fr': '6',
      'ja': '6',
      'ms': '6',
      'ru': '6',
      'vi': '6',
      'zh_Hans': '6个',
    },
    'sd11cfbx': {
      'ko': '6',
      'en': '6',
      'fr': '6',
      'ja': '6',
      'ms': '6',
      'ru': '6',
      'vi': '6',
      'zh_Hans': '6个',
    },
    'ef0vzsvi': {
      'ko': '6',
      'en': '6',
      'fr': '6',
      'ja': '6',
      'ms': '6',
      'ru': '6',
      'vi': '6',
      'zh_Hans': '6个',
    },
    '3oky0eco': {
      'ko': '6',
      'en': '6',
      'fr': '6',
      'ja': '6',
      'ms': '6',
      'ru': '6',
      'vi': '6',
      'zh_Hans': '6个',
    },
    '5vzxihzk': {
      'ko': '6',
      'en': '6',
      'fr': '6',
      'ja': '6',
      'ms': '6',
      'ru': '6',
      'vi': '6',
      'zh_Hans': '6个',
    },
    'nry9q8v6': {
      'ko': '6',
      'en': '6',
      'fr': '6',
      'ja': '6',
      'ms': '6',
      'ru': '6',
      'vi': '6',
      'zh_Hans': '6个',
    },
    '4xzn878w': {
      'ko': '7',
      'en': '7',
      'fr': '7',
      'ja': '7',
      'ms': '7',
      'ru': '7',
      'vi': '7',
      'zh_Hans': '7',
    },
    '2mmuul29': {
      'ko': '7',
      'en': '7',
      'fr': '7',
      'ja': '7',
      'ms': '7',
      'ru': '7',
      'vi': '7',
      'zh_Hans': '7',
    },
    'wqyv22if': {
      'ko': '7',
      'en': '7',
      'fr': '7',
      'ja': '7',
      'ms': '7',
      'ru': '7',
      'vi': '7',
      'zh_Hans': '7',
    },
    'maoidd9o': {
      'ko': '7',
      'en': '7',
      'fr': '7',
      'ja': '7',
      'ms': '7',
      'ru': '7',
      'vi': '7',
      'zh_Hans': '7',
    },
    'n9b4l7kw': {
      'ko': '7',
      'en': '7',
      'fr': '7',
      'ja': '7',
      'ms': '7',
      'ru': '7',
      'vi': '7',
      'zh_Hans': '7',
    },
    'pladh7ee': {
      'ko': '7',
      'en': '7',
      'fr': '7',
      'ja': '7',
      'ms': '7',
      'ru': '7',
      'vi': '7',
      'zh_Hans': '7',
    },
    'ju50skoy': {
      'ko': '7',
      'en': '7',
      'fr': '7',
      'ja': '7',
      'ms': '7',
      'ru': '7',
      'vi': '7',
      'zh_Hans': '7',
    },
    'pkklvkw5': {
      'ko': '7',
      'en': '7',
      'fr': '7',
      'ja': '7',
      'ms': '7',
      'ru': '7',
      'vi': '7',
      'zh_Hans': '7',
    },
    '1srvc43i': {
      'ko': '7',
      'en': '7',
      'fr': '7',
      'ja': '7',
      'ms': '7',
      'ru': '7',
      'vi': '7',
      'zh_Hans': '7',
    },
    'k0iq4o9f': {
      'ko': '8',
      'en': '8',
      'fr': '8',
      'ja': '8',
      'ms': '8',
      'ru': '8',
      'vi': 'số 8',
      'zh_Hans': '8个',
    },
    '9xuojcup': {
      'ko': '8',
      'en': '8',
      'fr': '8',
      'ja': '8',
      'ms': '8',
      'ru': '8',
      'vi': 'số 8',
      'zh_Hans': '8个',
    },
    'pr15e44l': {
      'ko': '8',
      'en': '8',
      'fr': '8',
      'ja': '8',
      'ms': '8',
      'ru': '8',
      'vi': 'số 8',
      'zh_Hans': '8个',
    },
    'tofayw5a': {
      'ko': '8',
      'en': '8',
      'fr': '8',
      'ja': '8',
      'ms': '8',
      'ru': '8',
      'vi': 'số 8',
      'zh_Hans': '8个',
    },
    'tpt2btx3': {
      'ko': '8',
      'en': '8',
      'fr': '8',
      'ja': '8',
      'ms': '8',
      'ru': '8',
      'vi': 'số 8',
      'zh_Hans': '8个',
    },
    'bilph4ax': {
      'ko': '8',
      'en': '8',
      'fr': '8',
      'ja': '8',
      'ms': '8',
      'ru': '8',
      'vi': 'số 8',
      'zh_Hans': '8个',
    },
    'z6jvj0tq': {
      'ko': '8',
      'en': '8',
      'fr': '8',
      'ja': '8',
      'ms': '8',
      'ru': '8',
      'vi': 'số 8',
      'zh_Hans': '8个',
    },
    '2l9u96cc': {
      'ko': '8',
      'en': '8',
      'fr': '8',
      'ja': '8',
      'ms': '8',
      'ru': '8',
      'vi': 'số 8',
      'zh_Hans': '8个',
    },
    'hr1l5dkd': {
      'ko': '8',
      'en': '8',
      'fr': '8',
      'ja': '8',
      'ms': '8',
      'ru': '8',
      'vi': 'số 8',
      'zh_Hans': '8个',
    },
    'f7lp7eg4': {
      'ko': '9',
      'en': '9',
      'fr': '9',
      'ja': '9',
      'ms': '9',
      'ru': '9',
      'vi': '9',
      'zh_Hans': '9',
    },
    't3v2uaf3': {
      'ko': '9',
      'en': '9',
      'fr': '9',
      'ja': '9',
      'ms': '9',
      'ru': '9',
      'vi': '9',
      'zh_Hans': '9',
    },
    '1igvxcv3': {
      'ko': '9',
      'en': '9',
      'fr': '9',
      'ja': '9',
      'ms': '9',
      'ru': '9',
      'vi': '9',
      'zh_Hans': '9',
    },
    's4y7lwv9': {
      'ko': '9',
      'en': '9',
      'fr': '9',
      'ja': '9',
      'ms': '9',
      'ru': '9',
      'vi': '9',
      'zh_Hans': '9',
    },
    't4x50owp': {
      'ko': '9',
      'en': '9',
      'fr': '9',
      'ja': '9',
      'ms': '9',
      'ru': '9',
      'vi': '9',
      'zh_Hans': '9',
    },
    'g9c0e9lx': {
      'ko': '9',
      'en': '9',
      'fr': '9',
      'ja': '9',
      'ms': '9',
      'ru': '9',
      'vi': '9',
      'zh_Hans': '9',
    },
    '7oqlxi8q': {
      'ko': '9',
      'en': '9',
      'fr': '9',
      'ja': '9',
      'ms': '9',
      'ru': '9',
      'vi': '9',
      'zh_Hans': '9',
    },
    'nmthum1u': {
      'ko': '9',
      'en': '9',
      'fr': '9',
      'ja': '9',
      'ms': '9',
      'ru': '9',
      'vi': '9',
      'zh_Hans': '9',
    },
    'm0xoq1bb': {
      'ko': '9',
      'en': '9',
      'fr': '9',
      'ja': '9',
      'ms': '9',
      'ru': '9',
      'vi': '9',
      'zh_Hans': '9',
    },
    'z8gkz65h': {
      'ko': 'Home',
      'en': 'Home',
      'fr': 'Domicile',
      'ja': 'ホーム',
      'ms': 'Rumah',
      'ru': 'Дом',
      'vi': 'Trang Chủ',
      'zh_Hans': '家',
    },
  },
  // join
  {
    'ktjjfrul': {
      'ko': '회원가입',
      'en': 'Sign Up',
      'fr': 'S\'inscrire',
      'ja': '会員登録',
      'ms': 'Daftar',
      'ru': 'Зарегистрироваться',
      'vi': 'Đăng ký',
      'zh_Hans': '报名',
    },
    'akcbkt8m': {
      'ko': '이메일',
      'en': 'email',
      'fr': 'e-mail',
      'ja': 'Eメール',
      'ms': 'emel',
      'ru': 'электронное письмо',
      'vi': 'e-mail',
      'zh_Hans': '电子邮件',
    },
    'yb74it82': {
      'ko': '이메일',
      'en': 'email',
      'fr': 'e-mail',
      'ja': 'Eメール',
      'ms': 'emel',
      'ru': 'электронное письмо',
      'vi': 'e-mail',
      'zh_Hans': '电子邮件',
    },
    'tf7l7v2t': {
      'ko': '비밀번호',
      'en': 'password',
      'fr': 'le mot de passe',
      'ja': 'パスワード',
      'ms': 'kata laluan',
      'ru': 'пароль',
      'vi': 'mật khẩu mở khóa',
      'zh_Hans': '密码',
    },
    '89h1lhsm': {
      'ko': '비밀번호',
      'en': 'password',
      'fr': 'le mot de passe',
      'ja': 'パスワード',
      'ms': 'kata laluan',
      'ru': 'пароль',
      'vi': 'mật khẩu mở khóa',
      'zh_Hans': '密码',
    },
    '4irfg2y7': {
      'ko': '비밀번호 확인',
      'en': 'verify password',
      'fr': 'vérifier le mot de passe',
      'ja': 'パスワード確認',
      'ms': 'sahkan kata laluan',
      'ru': 'подтвердите пароль',
      'vi': 'Xác nhận lại mật khẩu',
      'zh_Hans': '验证密码',
    },
    'qrlppp96': {
      'ko': '비밀번호 확인',
      'en': 'verify password',
      'fr': 'vérifier le mot de passe',
      'ja': 'パスワード確認',
      'ms': 'sahkan kata laluan',
      'ru': 'подтвердите пароль',
      'vi': 'Xác nhận lại mật khẩu',
      'zh_Hans': '验证密码',
    },
    '4thm49bt': {
      'ko': '회원가입',
      'en': 'Sign Up',
      'fr': 'S\'inscrire',
      'ja': '会員登録',
      'ms': 'Daftar',
      'ru': 'Зарегистрироваться',
      'vi': 'Đăng ký',
      'zh_Hans': '报名',
    },
    'n84awyoc': {
      'ko': '아이디/비밀번호 찾기',
      'en': 'Find ID/Password',
      'fr': 'Trouver identifiant/mot de passe',
      'ja': 'ID/パスワードを探す',
      'ms': 'Cari ID/Kata Laluan',
      'ru': 'Найти идентификатор/пароль',
      'vi': 'Tìm ID/Mật khẩu',
      'zh_Hans': '查找 ID/密码',
    },
    'o8a88mru': {
      'ko': '로그인',
      'en': 'log in',
      'fr': 'connexion',
      'ja': 'ログイン',
      'ms': 'log masuk',
      'ru': 'авторизоваться',
      'vi': 'đăng nhập',
      'zh_Hans': '登录',
    },
    'jng86e8x': {
      'ko': 'Home',
      'en': 'Home',
      'fr': 'Domicile',
      'ja': 'ホーム',
      'ms': 'Rumah',
      'ru': 'Дом',
      'vi': 'Trang Chủ',
      'zh_Hans': '家',
    },
  },
  // Gostudy
  {
    '2sssb2ts': {
      'ko': '단계 설정이\n완료되었습니다!',
      'en': 'step setting\nDone!',
      'fr': 'réglage de l\'étape\nFait!',
      'ja': 'ステップ設定\n完了しました！',
      'ms': 'penetapan langkah\nSelesai!',
      'ru': 'установка шага\nВыполнено!',
      'vi': 'cài đặt bước\nXong!',
      'zh_Hans': '步骤设置\n完毕！',
    },
    '9z2ebawt': {
      'ko': '회원가입 및 학습시작',
      'en': 'Register as a member and start learning',
      'fr': 'Inscrivez-vous en tant que membre et commencez à apprendre',
      'ja': '会員登録と学習開始',
      'ms': 'Daftar sebagai ahli dan mula belajar',
      'ru': 'Зарегистрируйтесь как участник и начните обучение',
      'vi': 'Đăng ký thành viên và bắt đầu học',
      'zh_Hans': '注册成为会员并开始学习',
    },
    '5igu1c7w': {
      'ko': 'GO!',
      'en': 'GO!',
      'fr': 'VA!',
      'ja': 'GO！',
      'ms': 'PERGI!',
      'ru': 'ИДТИ!',
      'vi': 'ĐI!',
      'zh_Hans': '走！',
    },
    'aijlw6fw': {
      'ko': 'Home',
      'en': 'Home',
      'fr': 'Domicile',
      'ja': 'ホーム',
      'ms': 'Rumah',
      'ru': 'Дом',
      'vi': 'Trang Chủ',
      'zh_Hans': '家',
    },
  },
  // Goal
  {
    '3r0sghpa': {
      'ko': '학습목표',
      'en': 'Learning Objectives',
      'fr': 'Objectifs d\'apprentissage',
      'ja': '学習目標',
      'ms': 'Objektif Pembelajaran',
      'ru': 'Цели обучения',
      'vi': 'Mục tiêu học tập',
      'zh_Hans': '学习目标',
    },
    'mq38gzt7': {
      'ko': '· 원어민 문장을 듣고 정확히 따라 할 수 있다',
      'en':
          '· You can listen to the sentences of native speakers and follow them exactly',
      'fr':
          '· Vous pouvez écouter les phrases de locuteurs natifs et les suivre exactement',
      'ja': '・ネイティブスピーカーの文章を聞いて正確に従うことができる',
      'ms':
          '· Anda boleh mendengar ayat penutur asli dan mengikutinya dengan tepat',
      'ru':
          '· Вы можете слушать предложения носителей языка и точно следовать им',
      'vi':
          '· Bạn có thể nghe những câu nói của người bản ngữ và nói theo một cách chính xác',
      'zh_Hans': '· 你可以听母语者的句子并准确地跟读',
    },
    'ayzoqpz3': {
      'ko': '· 일상 생활에서 자연스럽게 사용할 수 있다',
      'en': 'Can be used naturally in daily life',
      'fr': 'Peut être utilisé naturellement dans la vie quotidienne',
      'ja': '・日常生活で自然に使える',
      'ms': 'Boleh digunakan secara semulajadi dalam kehidupan seharian',
      'ru': 'Может использоваться естественным образом в повседневной жизни',
      'vi': 'Có thể được sử dụng tự nhiên trong cuộc sống hàng ngày',
      'zh_Hans': '可以在日常生活中自然使用',
    },
    'bflt9r44': {
      'ko': '· 원어민처럼 발음을 할 수 있다',
      'en': 'Can pronounce like a native speaker',
      'fr': 'Peut prononcer comme un locuteur natif',
      'ja': '・ネイティブスピーカーのように発音することができます',
      'ms': 'Boleh menyebut seperti penutur asli',
      'ru': 'Может произносить как носитель языка',
      'vi': 'Có thể phát âm như người bản ngữ',
      'zh_Hans': '可以像母语者一样发音',
    },
    'f73wzl4e': {
      'ko': '시작',
      'en': 'start',
      'fr': 'début',
      'ja': 'スタート',
      'ms': 'mulakan',
      'ru': 'Начало',
      'vi': 'bắt đầu',
      'zh_Hans': '开始',
    },
    '1i4u79ho': {
      'ko': 'Home',
      'en': 'Home',
      'fr': 'Domicile',
      'ja': 'ホーム',
      'ms': 'Rumah',
      'ru': 'Дом',
      'vi': 'Trang Chủ',
      'zh_Hans': '家',
    },
  },
  // checkaround
  {
    'k4kcpipb': {
      'ko': '주변이 조용한지 \n확인해주세요!',
      'en': 'Are the surroundings quiet?\nPlease check!',
      'fr': 'L\'environnement est-il calme ?\nVérifiez s\'il vous plaît!',
      'ja': '周囲が静か\n確認してください！',
      'ms': 'Adakah persekitaran sunyi?\nTolong periksa!',
      'ru': 'Вокруг тихо?\nПожалуйста, проверьте!',
      'vi': 'Xung quanh có yên tĩnh không?\nHãy kiểm tra!',
      'zh_Hans': '周围安静吗？\n请检查！',
    },
    'xa9crpih': {
      'ko': '자, 그럼 시작합니다',
      'en': 'So let\'s start',
      'fr': 'Alors commençons',
      'ja': 'さて、それから始めましょう。',
      'ms': 'Jadi mari kita mulakan',
      'ru': 'Итак, начнем',
      'vi': 'Vì vậy, hãy bắt đầu',
      'zh_Hans': '那么让我们开始吧',
    },
    'lkq4zi6x': {
      'ko': 'GO!',
      'en': 'GO!',
      'fr': 'VA!',
      'ja': 'GO！',
      'ms': 'PERGI!',
      'ru': 'ИДТИ!',
      'vi': 'ĐI!',
      'zh_Hans': '走！',
    },
    '1ntla6k2': {
      'ko': 'Home',
      'en': 'Home',
      'fr': 'Domicile',
      'ja': 'ホーム',
      'ms': 'Rumah',
      'ru': 'Дом',
      'vi': 'Trang Chủ',
      'zh_Hans': '家',
    },
  },
  // learnlist
  {
    '2qh9j1cc': {
      'ko': '과정 검색',
      'en': 'course search',
      'fr': 'recherche de cours',
      'ja': 'コース検索',
      'ms': 'carian kursus',
      'ru': 'поиск курса',
      'vi': 'tìm kiếm khóa học',
      'zh_Hans': '课程搜索',
    },
    'ka9wtriq': {
      'ko': 'Store/Location Name',
      'en': 'Store/Location Name',
      'fr': 'Nom du magasin/emplacement',
      'ja': 'Store/Location Name',
      'ms': 'Nama Kedai/Lokasi',
      'ru': 'Название магазина/местоположения',
      'vi': 'Tên cửa hàng/Địa điểm',
      'zh_Hans': '商店/地点名称',
    },
    'pg2sx8k5': {
      'ko': '123 Address St, City, ST',
      'en': '123 Address St, City, ST',
      'fr': '123 Adresse St, Ville, ST',
      'ja': '123 Address St, City, ST',
      'ms': '123 Alamat St, City, ST',
      'ru': '123 Address St, City, ST',
      'vi': 'Địa chỉ 123 St, Thành phố, ST',
      'zh_Hans': '123 Address St, City, ST',
    },
    '20jxn1ps': {
      'ko': '1.7mi',
      'en': '1.7mi',
      'fr': '2.7km',
      'ja': '1.7mi',
      'ms': '1.7bt',
      'ru': '2,7 мили',
      'vi': '1,7 dặm',
      'zh_Hans': '1.7英里',
    },
    'm1jb9tri': {
      'ko': 'Store/Location Name',
      'en': 'Store/Location Name',
      'fr': 'Nom du magasin/emplacement',
      'ja': 'Store/Location Name',
      'ms': 'Nama Kedai/Lokasi',
      'ru': 'Название магазина/местоположения',
      'vi': 'Tên cửa hàng/Địa điểm',
      'zh_Hans': '商店/位置名称',
    },
    'jxxunsn3': {
      'ko': '123 Address St, City, ST',
      'en': '123 Address St, City, ST',
      'fr': '123 Adresse St, Ville, ST',
      'ja': '123 Address St, City, ST',
      'ms': '123 Alamat St, City, ST',
      'ru': '123 Address St, City, ST',
      'vi': 'Địa chỉ 123 St, Thành phố, ST',
      'zh_Hans': '123 Address St, City, ST',
    },
    '12q451cc': {
      'ko': '1.7mi',
      'en': '1.7mi',
      'fr': '2.7km',
      'ja': '1.7mi',
      'ms': '1.7bt',
      'ru': '2,7 мили',
      'vi': '1,7 dặm',
      'zh_Hans': '1.7英里',
    },
    'uuvy4hid': {
      'ko': 'Store/Location Name',
      'en': 'Store/Location Name',
      'fr': 'Nom du magasin/emplacement',
      'ja': 'Store/Location Name',
      'ms': 'Nama Kedai/Lokasi',
      'ru': 'Название магазина/местоположения',
      'vi': 'Tên cửa hàng/Địa điểm',
      'zh_Hans': '商店/位置名称',
    },
    '7w62cpzy': {
      'ko': '123 Address St, City, ST',
      'en': '123 Address St, City, ST',
      'fr': '123 Adresse St, Ville, ST',
      'ja': '123 Address St, City, ST',
      'ms': '123 Alamat St, City, ST',
      'ru': '123 Address St, City, ST',
      'vi': 'Địa chỉ 123 St, Thành phố, ST',
      'zh_Hans': '123 Address St, City, ST',
    },
    'efvf1bnu': {
      'ko': '1.7mi',
      'en': '1.7mi',
      'fr': '2.7km',
      'ja': '1.7mi',
      'ms': '1.7bt',
      'ru': '2,7 мили',
      'vi': '1,7 dặm',
      'zh_Hans': '1.7英里',
    },
    'l0f473dr': {
      'ko': 'Store/Location Name',
      'en': 'Store/Location Name',
      'fr': 'Nom du magasin/emplacement',
      'ja': 'Store/Location Name',
      'ms': 'Nama Kedai/Lokasi',
      'ru': 'Название магазина/местоположения',
      'vi': 'Tên cửa hàng/Địa điểm',
      'zh_Hans': '商店/位置名称',
    },
    'zdektpa9': {
      'ko': '123 Address St, City, ST',
      'en': '123 Address St, City, ST',
      'fr': '123 Adresse St, Ville, ST',
      'ja': '123 Address St, City, ST',
      'ms': '123 Alamat St, City, ST',
      'ru': '123 Address St, City, ST',
      'vi': 'Địa chỉ 123 St, Thành phố, ST',
      'zh_Hans': '123 Address St, City, ST',
    },
    'mpd183zc': {
      'ko': '1.7mi',
      'en': '1.7mi',
      'fr': '2.7km',
      'ja': '1.7mi',
      'ms': '1.7bt',
      'ru': '2,7 мили',
      'vi': '1,7 dặm',
      'zh_Hans': '1.7英里',
    },
    '5liof4h2': {
      'ko': 'Shop',
      'en': 'Shop',
      'fr': 'Magasin',
      'ja': 'ショップ',
      'ms': 'Kedai',
      'ru': 'Магазин',
      'vi': 'Cửa hàng',
      'zh_Hans': '店铺',
    },
  },
  // freeSpeak
  {
    'e37u5dpy': {
      'ko': '제시문 듣기',
      'en': 'Listen to the proposal',
      'fr': 'Écoutez la proposition',
      'ja': '提示文を聞く',
      'ms': 'Dengar cadangan',
      'ru': 'Выслушайте предложение',
      'vi': 'Nghe lời đề nghị',
      'zh_Hans': '听取建议',
    },
    'rgp4fi7d': {
      'ko': '문장을 따라 말해보세요.',
      'en': 'Say it according to the sentence.',
      'fr': 'Dites-le selon la phrase.',
      'ja': '文章に従って教えてください。',
      'ms': 'Katakan mengikut ayat.',
      'ru': 'Скажи это согласно предложению.',
      'vi': 'Nói theo câu.',
      'zh_Hans': '按照句子说。',
    },
    'gyttmiio': {
      'ko': '문장확인',
      'en': 'sentence check',
      'fr': 'vérification de phrase',
      'ja': '文章確認',
      'ms': 'semak ayat',
      'ru': 'проверка предложений',
      'vi': 'kiểm tra câu',
      'zh_Hans': '句子检查',
    },
    'e2r7x14x': {
      'ko': '학습',
      'en': 'learning',
      'fr': 'apprentissage',
      'ja': '学習',
      'ms': 'pembelajaran',
      'ru': 'обучение',
      'vi': 'học hỏi',
      'zh_Hans': '学习',
    },
    'wpydkjxp': {
      'ko': 'Home',
      'en': 'Home',
      'fr': 'Domicile',
      'ja': 'ホーム',
      'ms': 'Rumah',
      'ru': 'Дом',
      'vi': 'Trang Chủ',
      'zh_Hans': '家',
    },
  },
  // freechecking
  {
    'a8p7lsln': {
      'ko': '원문 듣기',
      'en': 'Listen to original text',
      'fr': 'Écouter le texte original',
      'ja': '原文を聞く',
      'ms': 'Dengar teks asal',
      'ru': 'Прослушать исходный текст',
      'vi': 'Nghe văn bản gốc',
      'zh_Hans': '听原文',
    },
    'e8tcgtaz': {
      'ko': '이전',
      'en': 'Previous',
      'fr': 'Précédent',
      'ja': '以前',
      'ms': 'Sebelumnya',
      'ru': 'Предыдущий',
      'vi': 'Trước',
      'zh_Hans': '以前的',
    },
    'bowmhen1': {
      'ko': '다음',
      'en': 'next',
      'fr': 'suivant',
      'ja': 'Next',
      'ms': 'seterusnya',
      'ru': 'следующий',
      'vi': 'tiếp theo',
      'zh_Hans': '下一个',
    },
    'awp66eyp': {
      'ko': 'Home',
      'en': 'Home',
      'fr': 'Domicile',
      'ja': 'ホーム',
      'ms': 'Rumah',
      'ru': 'Дом',
      'vi': 'Trang Chủ',
      'zh_Hans': '家',
    },
  },
  // credit
  {
    '3j4yz1jl': {
      'ko': '결제수단 선택',
      'en': 'Select payment method',
      'fr': 'Sélectionnez le mode de paiement',
      'ja': '決済手段を選択',
      'ms': 'Pilih kaedah pembayaran',
      'ru': 'Выберите способ оплаты',
      'vi': 'Chọn phương thức thanh toán',
      'zh_Hans': '选择付款方式',
    },
    'f70sajha': {
      'ko': '신용·체크카드 결제',
      'en': 'Payment by credit/debit card',
      'fr': 'Paiement par carte de crédit/débit',
      'ja': 'クレジット・チェックカード決済',
      'ms': 'Pembayaran melalui kad kredit/debit',
      'ru': 'Оплата кредитной/дебетовой картой',
      'vi': 'Thanh toán bằng thẻ tín dụng/thẻ ghi nợ',
      'zh_Hans': '通过信用卡/借记卡付款',
    },
    'wugk1uc4': {
      'ko': '인앱 결제',
      'en': 'In-app billing',
      'fr': 'Facturation intégrée à l\'application',
      'ja': 'アプリ内課金',
      'ms': 'Pengebilan dalam apl',
      'ru': 'Биллинг в приложении',
      'vi': 'Thanh toán trong ứng dụng',
      'zh_Hans': '应用内结算',
    },
    '6susdka7': {
      'ko': 'Home',
      'en': 'Home',
      'fr': 'Domicile',
      'ja': 'ホーム',
      'ms': 'Rumah',
      'ru': 'Дом',
      'vi': 'Trang Chủ',
      'zh_Hans': '家',
    },
  },
  // home
  {
    '391uu3ge': {
      'ko': '학습 시작일(마지막 결제 기준일) : 2022.11.09',
      'en': 'Learning start date (last payment reference date): 2022.11.09',
      'fr':
          'Date de début d\'apprentissage (date de référence du dernier paiement) : 2022.11.09',
      'ja': '学習開始日（最終決済基準日）：2022.11.09',
      'ms':
          'Tarikh mula pembelajaran (tarikh rujukan pembayaran terakhir): 2022.11.09',
      'ru': 'Дата начала обучения (дата последнего платежа): 2022.11.09',
      'vi':
          'Ngày bắt đầu học (ngày tham chiếu thanh toán cuối cùng): 2022.11.09',
      'zh_Hans': '学习开始日期（最后付款参考日期）：2022.11.09',
    },
    'q7zao1v9': {
      'ko': '학습목표',
      'en': 'Learning Objectives',
      'fr': 'Objectifs d\'apprentissage',
      'ja': '学習目標',
      'ms': 'Objektif Pembelajaran',
      'ru': 'Цели обучения',
      'vi': 'Mục tiêu học tập',
      'zh_Hans': '学习目标',
    },
    'hnfxh7d3': {
      'ko': '· 원어민 문장을 듣고 정확히 따라 할 수 있다',
      'en':
          '· You can listen to the sentences of native speakers and follow them exactly',
      'fr':
          '· Vous pouvez écouter les phrases de locuteurs natifs et les suivre exactement',
      'ja': '・ネイティブスピーカーの文章を聞いて正確に従うことができる',
      'ms':
          '· Anda boleh mendengar ayat penutur asli dan mengikutinya dengan tepat',
      'ru':
          '· Вы можете слушать предложения носителей языка и точно следовать им',
      'vi':
          '· Bạn có thể nghe những câu nói của người bản ngữ và nói theo một cách chính xác',
      'zh_Hans': '· 你可以听母语者的句子并准确地跟读',
    },
    'tlmmyd5v': {
      'ko': '· 일상 생활에서 자연스럽게 사용할 수 있다',
      'en': 'Can be used naturally in daily life',
      'fr': 'Peut être utilisé naturellement dans la vie quotidienne',
      'ja': '・日常生活で自然に使える',
      'ms': 'Boleh digunakan secara semulajadi dalam kehidupan seharian',
      'ru': 'Может использоваться естественным образом в повседневной жизни',
      'vi': 'Có thể được sử dụng tự nhiên trong cuộc sống hàng ngày',
      'zh_Hans': '可以在日常生活中自然使用',
    },
    'lz01p4qi': {
      'ko': '· 원어민처럼 발음을 할 수 있다',
      'en': 'Can pronounce like a native speaker',
      'fr': 'Peut prononcer comme un locuteur natif',
      'ja': '・ネイティブスピーカーのように発音することができます',
      'ms': 'Boleh menyebut seperti penutur asli',
      'ru': 'Может произносить как носитель языка',
      'vi': 'Có thể phát âm như người bản ngữ',
      'zh_Hans': '可以像母语者一样发音',
    },
    'dknsedfg': {
      'ko': '학습 진행률',
      'en': 'learning progress',
      'fr': 'progrès de l\'apprentissage',
      'ja': '学習の進行状況',
      'ms': 'kemajuan pembelajaran',
      'ru': 'прогресс в обучении',
      'vi': 'tiến độ học tập',
      'zh_Hans': '学习进度',
    },
    'zj8aqy29': {
      'ko': '10/100',
      'en': '10/100',
      'fr': '10/100',
      'ja': '10/100',
      'ms': '10/100',
      'ru': '10/100',
      'vi': '10/100',
      'zh_Hans': '10/100',
    },
    'bo86dyo9': {
      'ko': '10%',
      'en': '10%',
      'fr': 'dix%',
      'ja': '10％',
      'ms': '10%',
      'ru': '10%',
      'vi': '10%',
      'zh_Hans': '10%',
    },
    'pftek3v3': {
      'ko': '한국어',
      'en': 'Korean',
      'fr': 'coréen',
      'ja': '韓国語',
      'ms': 'Korea',
      'ru': 'Корейский',
      'vi': 'Hàn Quốc',
      'zh_Hans': '韩国人',
    },
    'qslw18h3': {
      'ko': '영어',
      'en': 'english',
      'fr': 'Anglais',
      'ja': '英語',
      'ms': 'bahasa inggeris',
      'ru': 'английский',
      'vi': 'tiếng anh',
      'zh_Hans': '英语',
    },
    'mqzmkgye': {
      'ko': '중급',
      'en': 'Middle class',
      'fr': 'Classe moyenne',
      'ja': '中級',
      'ms': 'Kelas pertengahan',
      'ru': 'Средний класс',
      'vi': 'Tầng lớp trung lưu',
      'zh_Hans': '中产阶级',
    },
    '3p0psjkf': {
      'ko': '문형별',
      'en': 'Hyungbyeol Moon',
      'fr': 'Lune Hyungbyeol',
      'ja': '文型別',
      'ms': 'Hyungbyeol Moon',
      'ru': 'Хёнбёль Мун',
      'vi': 'Mặt trăng Hyungbyeol',
      'zh_Hans': '文亨星',
    },
    'g3elb0sg': {
      'ko': '5단 8형',
      'en': '5 stage 8 type',
      'fr': 'Type 5 étapes 8',
      'ja': '5段8形',
      'ms': '5 peringkat 8 jenis',
      'ru': '5 этап 8 тип',
      'vi': '5 giai đoạn 8 loại',
      'zh_Hans': '5级8型',
    },
    'nzbzdkpr': {
      'ko': '학습하기',
      'en': 'learning',
      'fr': 'apprentissage',
      'ja': '学習する',
      'ms': 'pembelajaran',
      'ru': 'обучение',
      'vi': 'học hỏi',
      'zh_Hans': '学习',
    },
    '2in06tpp': {
      'ko': '마이페이지',
      'en': 'my page',
      'fr': 'ma page',
      'ja': 'マイページ',
      'ms': 'halaman saya',
      'ru': 'моя страница',
      'vi': 'trang của tôi',
      'zh_Hans': '我的页面',
    },
    'f1e9l0t6': {
      'ko': '언어 설정',
      'en': 'language settings',
      'fr': 'paramètres de langue',
      'ja': '言語設定',
      'ms': 'tetapan bahasa',
      'ru': 'языковые настройки',
      'vi': 'cài đặt ngôn ngữ',
      'zh_Hans': '语言设定',
    },
    '6upkci5d': {
      'ko': 'Home',
      'en': 'Home',
      'fr': 'Domicile',
      'ja': 'ホーム',
      'ms': 'Rumah',
      'ru': 'Дом',
      'vi': 'Trang Chủ',
      'zh_Hans': '家',
    },
  },
  // profile
  {
    '4sya0xe9': {
      'ko': '홍길동님',
      'en': 'Hong Gil-dong',
      'fr': 'Hong Gil-dong',
      'ja': 'ホンギルドン',
      'ms': 'Hong Gil-dong',
      'ru': 'Хон Гиль-дон',
      'vi': 'Hong Gil-dong',
      'zh_Hans': '洪吉东',
    },
    '6jiuxk6w': {
      'ko': '무료 회원이에요!',
      'en': 'You are a free member!',
      'fr': 'Vous êtes un membre gratuit !',
      'ja': '無料会員です！',
      'ms': 'Anda ahli percuma!',
      'ru': 'Вы свободный участник!',
      'vi': 'Bạn là một thành viên miễn phí!',
      'zh_Hans': '您是免费会员！',
    },
    'kuy3ut80': {
      'ko': '유료 회원 결제하기',
      'en': 'Pay for paid membership',
      'fr': 'Payer pour un abonnement payant',
      'ja': '有料会員決済',
      'ms': 'Bayar untuk keahlian berbayar',
      'ru': 'Оплатить платное членство',
      'vi': 'Thanh toán cho thành viên trả phí',
      'zh_Hans': '支付付费会员费',
    },
    'w5iokt8r': {
      'ko': '설정',
      'en': 'Settings',
      'fr': 'Réglages',
      'ja': '設定',
      'ms': 'tetapan',
      'ru': 'Настройки',
      'vi': 'Cài đặt',
      'zh_Hans': '设置',
    },
    'lp9oji3i': {
      'ko': '결제 내역',
      'en': 'payment details',
      'fr': 'historique de paiement',
      'ja': 'お支払い履歴',
      'ms': 'sejarah pembayaran',
      'ru': 'История платежей',
      'vi': 'chi tiết thanh toán',
      'zh_Hans': '支付历史',
    },
    'eayorkhq': {
      'ko': 'Home',
      'en': 'Home',
      'fr': 'Domicile',
      'ja': 'ホーム',
      'ms': 'Rumah',
      'ru': 'Дом',
      'vi': 'Trang Chủ',
      'zh_Hans': '家',
    },
  },
  // editProfile
  {
    'hlkwrnvb': {
      'ko': '프로필 편집',
      'en': 'Edit Profile',
      'fr': 'Editer le profil',
      'ja': 'プロフィールの編集',
      'ms': 'Sunting profil',
      'ru': 'Редактировать профиль',
      'vi': 'Chỉnh sửa hồ sơ',
      'zh_Hans': '编辑个人资料',
    },
    '0e6yzcw5': {
      'ko': '이름',
      'en': 'name',
      'fr': 'Nom',
      'ja': '名前',
      'ms': 'nama',
      'ru': 'имя',
      'vi': 'Tên',
      'zh_Hans': '姓名',
    },
    'k6aw86jv': {
      'ko': '홍길동',
      'en': 'Hong Gil Dong',
      'fr': 'Hong Gil Dong',
      'ja': 'ホンギルドン',
      'ms': 'Hong Gil Dong',
      'ru': 'Хон Гиль Донг',
      'vi': 'Hồng Gil Dong',
      'zh_Hans': '洪吉东',
    },
    'jt6hkfiz': {
      'ko': '이메일',
      'en': 'email',
      'fr': 'e-mail',
      'ja': 'Eメール',
      'ms': 'emel',
      'ru': 'электронное письмо',
      'vi': 'e-mail',
      'zh_Hans': '电子邮件',
    },
    'nz9pew5f': {
      'ko': 'gildong@naver.com',
      'en': 'gildong@naver.com',
      'fr': 'gildong@naver.com',
      'ja': 'gildong@naver.com',
      'ms': 'gildong@naver.com',
      'ru': 'gildong@naver.com',
      'vi': 'gildong@naver.com',
      'zh_Hans': 'gildong@naver.com',
    },
    'x4cyd46w': {
      'ko': '연락처',
      'en': 'contact',
      'fr': 'Contactez',
      'ja': 'お問い合わせ',
      'ms': 'kenalan',
      'ru': 'контакт',
      'vi': 'liên hệ',
      'zh_Hans': '接触',
    },
    '1103bega': {
      'ko': '01012345678',
      'en': '01012345678',
      'fr': '01012345678',
      'ja': '01012345678',
      'ms': '01012345678',
      'ru': '01012345678',
      'vi': '01012345678',
      'zh_Hans': '01012345678',
    },
    'l33me5h8': {
      'ko': '수정',
      'en': 'Modify',
      'fr': 'Modifier',
      'ja': '修正',
      'ms': 'Ubah suai',
      'ru': 'Изменить',
      'vi': 'Biến đổi',
      'zh_Hans': '调整',
    },
    'n75hxwgt': {
      'ko': 'Home',
      'en': 'Home',
      'fr': 'Domicile',
      'ja': 'ホーム',
      'ms': 'Rumah',
      'ru': 'Дом',
      'vi': 'Trang Chủ',
      'zh_Hans': '家',
    },
  },
  // setting
  {
    'bkhz8gyh': {
      'ko': '앱 설정',
      'en': 'app settings',
      'fr': 'paramètres de l\'application',
      'ja': 'アプリ設定',
      'ms': 'tetapan aplikasi',
      'ru': 'настройки приложения',
      'vi': 'cài đặt ứng dụng',
      'zh_Hans': '应用程序设置',
    },
    'ymd6n8jn': {
      'ko': '앱 푸시 알림',
      'en': 'app push notification',
      'fr': 'notification push de l\'application',
      'ja': 'アプリプッシュ通知',
      'ms': 'pemberitahuan tolak apl',
      'ru': 'push-уведомление приложения',
      'vi': 'thông báo đẩy ứng dụng',
      'zh_Hans': '应用推送通知',
    },
    'q05h6hyj': {
      'ko': '마케팅/이벤트 알림',
      'en': 'Marketing/event notification',
      'fr': 'Marketing/notification d\'événements',
      'ja': 'マーケティング/イベント通知',
      'ms': 'Pemberitahuan pemasaran/acara',
      'ru': 'Уведомление о маркетинге/событии',
      'vi': 'Thông báo tiếp thị/sự kiện',
      'zh_Hans': '营销/活动通知',
    },
    '6uy7m59r': {
      'ko': '서비스 이용약관',
      'en': 'Terms of Service',
      'fr': 'Conditions d\'utilisation',
      'ja': 'サービス利用規約',
      'ms': 'Syarat Perkhidmatan',
      'ru': 'условия обслуживания',
      'vi': 'Điều khoản dịch vụ',
      'zh_Hans': '服务条款',
    },
    'a9z4agkw': {
      'ko': '개인정보 처리방침',
      'en': 'privacy policy',
      'fr': 'politique de confidentialité',
      'ja': '個人情報処理方針',
      'ms': 'dasar privasi',
      'ru': 'политика конфиденциальности',
      'vi': 'Chính sách bảo mật',
      'zh_Hans': '隐私政策',
    },
    '2linrtic': {
      'ko': '버전 정보(1.0.1)',
      'en': 'Version information (1.0.1)',
      'fr': 'Informations sur la version (1.0.1)',
      'ja': 'バージョン情報（1.0.1）',
      'ms': 'Maklumat versi (1.0.1)',
      'ru': 'Информация о версии (1.0.1)',
      'vi': 'Thông tin phiên bản (1.0.1)',
      'zh_Hans': '版本信息 (1.0.1)',
    },
    'g3lqegf6': {
      'ko': '최신 버전으로 업데이트',
      'en': 'update to latest version',
      'fr': 'mise à jour vers la dernière version',
      'ja': '最新バージョンにアップデート',
      'ms': 'kemas kini kepada versi terkini',
      'ru': 'обновить до последней версии',
      'vi': 'cập nhật lên phiên bản mới nhất',
      'zh_Hans': '更新到最新版本',
    },
    'zkk6yr37': {
      'ko': 'Home',
      'en': 'Home',
      'fr': 'Domicile',
      'ja': 'ホーム',
      'ms': 'Rumah',
      'ru': 'Дом',
      'vi': 'Trang Chủ',
      'zh_Hans': '家',
    },
  },
  // creditHistory
  {
    'hkh26o08': {
      'ko': '구매 내역',
      'en': 'purchase history',
      'fr': 'historique d\'achat',
      'ja': '購入履歴',
      'ms': 'sejarah pembelian',
      'ru': 'История покупок',
      'vi': 'lịch sử thanh toán',
      'zh_Hans': '购买记录',
    },
    'kckxzwpk': {
      'ko': '결제 내역이 없습니다',
      'en': 'No payment history',
      'fr': 'Aucun historique de paiement',
      'ja': 'お支払い履歴はありません',
      'ms': 'Tiada sejarah pembayaran',
      'ru': 'Нет истории платежей',
      'vi': 'Không có lịch sử thanh toán',
      'zh_Hans': '没有付款记录',
    },
    'k5vamq5o': {
      'ko': 'Home',
      'en': 'Home',
      'fr': 'Domicile',
      'ja': 'ホーム',
      'ms': 'Rumah',
      'ru': 'Дом',
      'vi': 'Trang Chủ',
      'zh_Hans': '家',
    },
  },
  // text
  {
    '5aikgxwk': {
      'ko': 'Home',
      'en': 'Home',
      'fr': 'Domicile',
      'ja': 'ホーム',
      'ms': 'Rumah',
      'ru': 'Дом',
      'vi': 'Trang Chủ',
      'zh_Hans': '家',
    },
  },
  // freepopup
  {
    'ealifal6': {
      'ko': '효과적인 학습을 위하여',
      'en': 'for effective learning',
      'fr': 'pour un apprentissage efficace',
      'ja': '効果的な学習のために',
      'ms': 'untuk pembelajaran yang berkesan',
      'ru': 'для эффективного обучения',
      'vi': 'để học hiệu quả',
      'zh_Hans': '有效学习',
    },
    'sjvgs2u1': {
      'ko':
          '학습효과의 극대화를 위해서 각 문장마다 원어민 문장을 들으신 후에는 꼭 따라서 말하기(SHADOWING)를 권장합니다.',
      'en':
          'To maximize the learning effect, we recommend SHADOWING after listening to the native speaker\'s sentence for each sentence.',
      'fr':
          'Pour maximiser l\'effet d\'apprentissage, nous vous recommandons d\'OMBRER après avoir écouté la phrase du locuteur natif pour chaque phrase.',
      'ja':
          '学習効果の最大化のために、各文章ごとにネイティブスピーカーの文章を聞いた後は、必ずしたがって話す（SHADOWING）をお勧めします。',
      'ms':
          'Untuk memaksimumkan kesan pembelajaran, kami mengesyorkan MEMBAYANG selepas mendengar ayat penutur asli untuk setiap ayat.',
      'ru':
          'Чтобы максимизировать эффект обучения, мы рекомендуем SHADOWING после прослушивания предложения носителя языка для каждого предложения.',
      'vi':
          'Để tối đa hóa hiệu quả học tập, chúng tôi khuyên bạn nên SHADOWING sau khi nghe cách nói của người bản xứ cho từng câu.',
      'zh_Hans': '为了最大限度地提高学习效果，我们建议在听完母语人士的句子后对每个句子进行 SHADOWING。',
    },
    'xtz00hit': {
      'ko': '확인',
      'en': 'Confirm',
      'fr': 'Confirmer',
      'ja': '確認',
      'ms': 'sahkan',
      'ru': 'Подтверждать',
      'vi': 'Xác nhận',
      'zh_Hans': '确认',
    },
  },
  // creditpopup
  {
    'hd03tvhk': {
      'ko': '여기서부턴 유료에요',
      'en': 'It\'s paid here.',
      'fr': 'C\'est payé ici.',
      'ja': 'ここからは有料です。',
      'ms': 'Ia dibayar di sini.',
      'ru': 'Здесь платно.',
      'vi': 'Nó được trả ở đây.',
      'zh_Hans': '在这里付钱。',
    },
    'rozotsu1': {
      'ko':
          '아쉽게도 무료 기본예문 학습은 여기까지에요.\n더 많은 학습을 하기 위해선 결제가 필요해요.\n\n※개별과정당 학습제한시간 : 1개월\n   (개별과정당 100문항)',
      'en':
          'Unfortunately, this is the end of free basic example sentence learning.\nPayment is required to learn more.\n\n※Learning time limit per individual course: 1 month\n   (100 questions per individual course)',
      'fr':
          'Malheureusement, c\'est la fin de l\'apprentissage gratuit des phrases d\'exemple de base.\nLe paiement est requis pour en savoir plus.\n\n※Délai d\'apprentissage par cours individuel : 1 mois\n   (100 questions par cours individuel)',
      'ja':
          '残念ながら、無料の基本例文学習はここまでです。\nより多くの学習をするためには決済が必要です。\n\n※個別課程当たり学習制限時間：1ヶ月\n   （個別課程当たり100問）',
      'ms':
          'Malangnya, ini adalah penghujung pembelajaran ayat contoh asas percuma.\nBayaran diperlukan untuk mengetahui lebih lanjut.\n\n※Had masa pembelajaran setiap kursus individu: 1 bulan\n   (100 soalan setiap kursus individu)',
      'ru':
          'К сожалению, это конец бесплатного изучения базовых примеров предложений.\nПлата требуется, чтобы узнать больше.\n\n※ Срок обучения для каждого отдельного курса: 1 месяц\n   (100 вопросов на индивидуальный курс)',
      'vi':
          'Thật không may, đây là phần cuối của việc học câu ví dụ cơ bản miễn phí.\nThanh toán là cần thiết để tìm hiểu thêm.\n\n※Giới hạn thời gian học cho mỗi khóa học cá nhân: 1 tháng\n   (100 câu hỏi cho mỗi khóa học cá nhân)',
      'zh_Hans':
          '不幸的是，这是免费的基本例句学习的结束。\n需要付费才能了解更多。\n\n※每门课程学习时限：1个月\n   （每门课程 100 个问题）',
    },
    'mbcnv5sf': {
      'ko': '끝내기',
      'en': 'finish',
      'fr': 'terminer',
      'ja': '終了',
      'ms': 'selesai',
      'ru': 'финиш',
      'vi': 'Kết thúc',
      'zh_Hans': '结束',
    },
    'ldet0alq': {
      'ko': '결제',
      'en': 'payment',
      'fr': 'Paiement',
      'ja': 'お支払い',
      'ms': 'bayaran',
      'ru': 'оплата',
      'vi': 'sự chi trả',
      'zh_Hans': '支付',
    },
  },
  // startpopup
  {
    'n4m7jmua': {
      'ko': '구구단스피킹 학습법',
      'en': 'Multiplication table speaking learning method',
      'fr': 'Table de multiplication méthode d\'apprentissage de l\'oral',
      'ja': 'ググダンスピーキング学習法',
      'ms': 'Kaedah pembelajaran bertutur jadual darab',
      'ru': 'Метод обучения разговорной таблице умножения',
      'vi': 'Phương pháp học nói bảng cửu chương',
      'zh_Hans': '乘法表口语学习方法',
    },
    '9yint7cz': {
      'ko':
          '1. 한글 제시문을 들은 후 \'삐(BEEP)\' 소리가 나면 영어로 발화하세요.\n\n2. \'문장확인\' 버튼으로 원문과 자신의 발화문을 비교확인하세요.\n\n3. 문장 앞의 들어보기 아이콘으로 문장의 음성을 확인하세요.\n\n4. 원문청취 후 따라서 말하기(SHADOWING)를 하세요.\n\n5. 화면하단에서 \'다음번호\'를 누르세요.',
      'en':
          '1. After listening to the Korean text, speak in English when you hear a \'BEEP\' sound.\n\n2. Compare and check the original text and your own utterance with the \'Check Sentence\' button.\n\n3. Check the voice of the sentence with the listen icon in front of the sentence.\n\n4. After listening to the original text, do SHADOWING.\n\n5. Press \'next number\' at the bottom of the screen.',
      'fr':
          '1. Après avoir écouté le texte coréen, parlez en anglais lorsque vous entendez un son « BIP ».\n\n2. Comparez et vérifiez le texte original et votre propre énoncé avec le bouton \'Vérifier la phrase\'.\n\n3. Vérifiez la voix de la phrase avec l\'icône d\'écoute devant la phrase.\n\n4. Après avoir écouté le texte original, faites de l\'OMBRAGE.\n\n5. Appuyez sur \'numéro suivant\' en bas de l\'écran.',
      'ja':
          '1. ハングルの提示文を聞いた後、「ピー（BEEP）」の音が出たら英語で発話してください。\n\n2. 「文章確認」ボタンで原文と自分の発話文を比較確認してください。\n\n3. 文章の前の聞き取りアイコンで文章の音声を確認します。\n\n4. 原文聴取後、したがって話す（SHADOWING）をしてください。\n\n5. 画面下部で「次の番号」をタップします。',
      'ms':
          '1. Selepas mendengar teks Korea, bercakap dalam bahasa Inggeris apabila anda mendengar bunyi \'BEEP\'.\n\n2. Bandingkan dan semak teks asal dan ujaran anda sendiri dengan butang \'Semak Ayat\'.\n\n3. Semak suara ayat dengan ikon dengar di hadapan ayat.\n\n4. Selepas mendengar teks asal, lakukan BAYANGAN.\n\n5. Tekan \'nombor seterusnya\' di bahagian bawah skrin.',
      'ru':
          '1. Прослушав корейский текст, говорите по-английски, когда услышите звуковой сигнал.\n\n2. Сравните и проверьте исходный текст и собственное высказывание с помощью кнопки «Проверить предложение».\n\n3. Проверьте голос предложения с помощью значка прослушивания перед предложением.\n\n4. Прослушав исходный текст, выполните ЗАТЕНЕНИЕ.\n\n5. Нажмите «следующий номер» внизу экрана.',
      'vi':
          '1. Sau khi nghe đoạn văn bản tiếng Hàn, hãy nói bằng tiếng Anh khi bạn nghe thấy âm thanh \'BÍP\'.\n\n2. So sánh và kiểm tra văn bản gốc và cách nói của chính bạn bằng nút \'Kiểm tra câu\'.\n\n3. Kiểm tra giọng nói của câu bằng biểu tượng nghe trước câu.\n\n4. Sau khi nghe văn bản gốc, hãy CHỤP HÌNH.\n\n5. Nhấn \'số tiếp theo\' ở cuối màn hình.',
      'zh_Hans':
          '1. 听完韩语课文，听到“BEEP”声后，再说英语。\n\n2. 使用“检查句子”按钮对原文和自己的话语进行比较和检查。\n\n3.用句子前面的听图标检查句子的声音。\n\n4.听完原文，做影子。\n\n5. 按屏幕底部的“下一个号码”。',
    },
    'yjaggmgr': {
      'ko': '시작',
      'en': 'start',
      'fr': 'début',
      'ja': 'スタート',
      'ms': 'mulakan',
      'ru': 'Начало',
      'vi': 'bắt đầu',
      'zh_Hans': '开始',
    },
  },
  // upmiddlepopup
  {
    'tt3nrvb7': {
      'ko': '주의해주세요!',
      'en': 'Please be careful!',
      'fr': 'S\'il vous plaît soyez prudente!',
      'ja': 'ご注意ください！',
      'ms': 'Tolong berhati-hati!',
      'ru': 'Пожалуйста, будь осторожен!',
      'vi': 'Hãy cẩn thận!',
      'zh_Hans': '请小心！',
    },
    'fxm52ura': {
      'ko':
          '중급 이상의 경우 학습 중 언어간 다른 어법규칙이나 관습적 표현, 발음상 편리함 등으로 문장 발화시 다소 다른 배열로 표현되는 문장들이 있을 수 있습니다.',
      'en':
          'In the case of the intermediate level or higher, there may be sentences that are expressed in slightly different arrangements when pronouncing sentences due to different grammar rules, customary expressions, and pronunciation convenience among languages during learning.',
      'fr':
          'Dans le cas du niveau intermédiaire ou supérieur, il peut y avoir des phrases qui sont exprimées dans des arrangements légèrement différents lors de la prononciation des phrases en raison de règles de grammaire différentes, d\'expressions coutumières et de commodité de prononciation entre les langues pendant l\'apprentissage.',
      'ja':
          '中級以上の場合、学習中の言語間の異なる語法規則や慣習的な表現、発音上の利便性などで、文章発話時に多少異なる配列で表現される文章がある場合があります。',
      'ms':
          'Dalam kes peringkat pertengahan atau lebih tinggi, mungkin terdapat ayat yang dinyatakan dalam susunan yang sedikit berbeza semasa menyebut ayat disebabkan oleh peraturan tatabahasa yang berbeza, ungkapan adat, dan kemudahan sebutan antara bahasa semasa pembelajaran.',
      'ru':
          'В случае среднего уровня или выше могут быть предложения, которые выражены в несколько иной аранжировке при произнесении предложений из-за разных правил грамматики, общеупотребительных выражений и удобства произношения среди языков во время обучения.',
      'vi':
          'Đối với trình độ trung cấp trở lên, có thể có những câu được diễn đạt theo cách sắp xếp hơi khác khi phát âm câu do các quy tắc ngữ pháp khác nhau, phong tục tập quán và sự thuận tiện trong cách phát âm giữa các ngôn ngữ trong quá trình học.',
      'zh_Hans':
          '在中级以上的情况下，由于语言在学习过程中语法规则、习惯用语、发音便利性等不同，可能会出现句子发音时表达排列略有不同的情况。',
    },
    '1m7mcsj2': {
      'ko': '확인',
      'en': 'Confirm',
      'fr': 'Confirmer',
      'ja': '確認',
      'ms': 'sahkan',
      'ru': 'Подтверждать',
      'vi': 'Xác nhận',
      'zh_Hans': '确认',
    },
  },
  // findidpopup
  {
    's4q03kyg': {
      'ko': '아이디 찾기',
      'en': 'find ID',
      'fr': 'trouver l\'identifiant',
      'ja': 'IDを探す',
      'ms': 'cari ID',
      'ru': 'найти идентификатор',
      'vi': 'tìm ID',
      'zh_Hans': '找身份证',
    },
    'p32tm3e7': {
      'ko': '고객님의 아이디는 gildong@naver.com입니다.',
      'en': 'Your ID is gildong@naver.com.',
      'fr': 'Votre identifiant est gildong@naver.com.',
      'ja': 'あなたのIDはgildong@naver.comです。',
      'ms': 'ID anda ialah gildong@naver.com.',
      'ru': 'Ваш идентификатор: gildong@naver.com.',
      'vi': 'ID của bạn là gildong@naver.com.',
      'zh_Hans': '您的 ID 是 gildong@naver.com。',
    },
    '1q0gw7kp': {
      'ko': '확인',
      'en': 'Confirm',
      'fr': 'Confirmer',
      'ja': '確認',
      'ms': 'sahkan',
      'ru': 'Подтверждать',
      'vi': 'Xác nhận',
      'zh_Hans': '确认',
    },
  },
  // bottom
  {
    'sk7csitk': {
      'ko': 'Hello World',
      'en': 'Hello World',
      'fr': 'Bonjour le monde',
      'ja': 'Hello World',
      'ms': 'Hai dunia',
      'ru': 'Привет, мир',
      'vi': 'Chào thế giới',
      'zh_Hans': '你好世界',
    },
    'svdgz2t5': {
      'ko': 'Hello World',
      'en': 'Hello World',
      'fr': 'Bonjour le monde',
      'ja': 'Hello World',
      'ms': 'Hai dunia',
      'ru': 'Привет, мир',
      'vi': 'Chào thế giới',
      'zh_Hans': '你好世界',
    },
    'luf78u8g': {
      'ko': '확인',
      'en': 'Confirm',
      'fr': 'Confirmer',
      'ja': '確認',
      'ms': 'sahkan',
      'ru': 'Подтверждать',
      'vi': 'Xác nhận',
      'zh_Hans': '确认',
    },
  },
  // Miscellaneous
  {
    '80enwdh7': {
      'ko': '권한 이용에 동의해주세요.',
      'en': '',
      'fr': '',
      'ja': '',
      'ms': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
    },
    'zlv5kcp6': {
      'ko': '권한 이용에 동의해주세요.',
      'en': '',
      'fr': '',
      'ja': '',
      'ms': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
    },
    'nprrn934': {
      'ko': '',
      'en': '',
      'fr': '',
      'ja': '',
      'ms': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
    },
    '1p8saijc': {
      'ko': '',
      'en': '',
      'fr': '',
      'ja': '',
      'ms': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
    },
    'ci3srnzi': {
      'ko': '',
      'en': '',
      'fr': '',
      'ja': '',
      'ms': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
    },
    'ein5ubir': {
      'ko': '',
      'en': '',
      'fr': '',
      'ja': '',
      'ms': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
    },
    '53l2lkfo': {
      'ko': '',
      'en': '',
      'fr': '',
      'ja': '',
      'ms': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
    },
    '75fj02h6': {
      'ko': '',
      'en': '',
      'fr': '',
      'ja': '',
      'ms': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
    },
    'g51qqysm': {
      'ko': '',
      'en': '',
      'fr': '',
      'ja': '',
      'ms': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
    },
    'pa4r7n68': {
      'ko': '',
      'en': '',
      'fr': '',
      'ja': '',
      'ms': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
    },
    'l5ajdixo': {
      'ko': '',
      'en': '',
      'fr': '',
      'ja': '',
      'ms': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
    },
    'hbyazxwq': {
      'ko': '',
      'en': '',
      'fr': '',
      'ja': '',
      'ms': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
    },
    'fb6v0pxt': {
      'ko': '',
      'en': '',
      'fr': '',
      'ja': '',
      'ms': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
    },
    'oxm0ypty': {
      'ko': '',
      'en': '',
      'fr': '',
      'ja': '',
      'ms': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
    },
    'c1j1ow0o': {
      'ko': '',
      'en': '',
      'fr': '',
      'ja': '',
      'ms': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
    },
    'ltqczjj2': {
      'ko': '',
      'en': '',
      'fr': '',
      'ja': '',
      'ms': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
    },
    '5121ne8g': {
      'ko': '',
      'en': '',
      'fr': '',
      'ja': '',
      'ms': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
    },
    'ql8pbcr3': {
      'ko': '',
      'en': '',
      'fr': '',
      'ja': '',
      'ms': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
    },
    '0skzlums': {
      'ko': '',
      'en': '',
      'fr': '',
      'ja': '',
      'ms': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
    },
    'y7kh5nlp': {
      'ko': '',
      'en': '',
      'fr': '',
      'ja': '',
      'ms': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
    },
    'bftouphr': {
      'ko': '',
      'en': '',
      'fr': '',
      'ja': '',
      'ms': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
    },
    'fmspdeia': {
      'ko': '',
      'en': '',
      'fr': '',
      'ja': '',
      'ms': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
    },
  },
].reduce((a, b) => a..addAll(b));
